### ISSUE TITLE
Since a few days the bouquets are not loading

### ISSUE THREAD

**Issue by 40H3X** [E2OpenPlugins/e2openplugin-OpenWebif#1560]
![Vu-Uno4K-SE-OpenWebif](https://user-images.githubusercontent.com/73245215/187169209-761ad214-e9f6-444e-9cc1-42e07fe381fa.jpg)

Below enigma debuglog from OpenPLi
`
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 2155, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 2284, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 946, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 235, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 302, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 209, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/ajax.py", line 86, in P_channels
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/services.py", line 473, in getChannels
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/epg.py", line 278, in getMultiChannelNowNextEvents
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/epg.py", line 184, in _queryEPG
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/epg.py", line 174, in _transformEventData
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/epgevent.py", line 258, in __init__
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/epgevent.py", line 111, in getCustomTimeFormats
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/epgevent.py", line 96, in getDisplayday
    
  File "/usr/lib/enigma2/python/Components/config.py", line 1765, in __getattr__
    
exceptions.AttributeError: date`

**Comment by WanWizard** [comment]
Also uses reported some API functions as broken.

**Comment by jbleyel** [comment]
This should be fixed already here -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/bd4c4f6360e41915fd8e98afc9b68a3ebbb4fdce

**Comment by WanWizard** [comment]
That catches KeyError, but the error here is AttributeError.

**Comment by jbleyel** [comment]
Can you add the AttributeError?

**Comment by WanWizard** [comment]
Changing it to:
````
except (KeyError, AttributeError):
````
fixes the issue.
