### ISSUE TITLE
openwebif movie browser bug

### ISSUE THREAD

**Issue by kolomparrudi** [E2OpenPlugins/e2openplugin-OpenWebif#337]
Hi,

I found a bug in openwebif:
when I want to play my recorded movies from a directory containts non english (hungarian: á é ó ő ű í) characters openwebif crashes when I select the directory. Here is the crash log:

<  8391.692> Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived

  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived

  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived

  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived

--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process

  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render

  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 109, in render
    data = func(request)
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/ajax.py", line 153, in P_movies
    movies = getMovieList(request.args["dirname"][0])
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/movies.py", line 114, in getMovieList
    bookmarklist=[x for x in listdir(directory) if (x[0] != '.' and (isdir(join(directory, x)) or (islink(join(directory, x)) and exists(join(directory, x)))))]
exceptions.OSError: [Errno 2] No such file or directory: '/media/hdd/Bar\xe1tok k\xf6zt/'

The directory name: /mnt/hdd/Barátok közt (UTF-8 encoded).

Br,
Laszlo

**Comment by jbleyel** [comment]
Please use the lateste version an try again.

**Comment by kolomparrudi** [comment]
Sorry for the late answer, but the issue is still not solved, here is my log:
nownext finished(1478615312)
<317212.235> Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived

  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived

  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived

  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived

--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process

  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render

  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 121, in render
    data = func(request)
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/ajax.py", line 157, in P_movies
    movies = getMovieList(request.args["dirname"][0])
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/movies.py", line 114, in getMovieList
    bookmarklist=[x for x in listdir(directory) if (x[0] != '.' and (isdir(join(directory, x)) or (islink(join(directory, x)) and exists(join(directory, x)))))]
exceptions.OSError: [Errno 2] No such file or directory: '/media/hdd/Bar\xe1tok k\xf6zt/'
<317215.326> [eEPGCache] schedule finished(1478615326)
<317216.266> connectionLost? [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]<317216.266>

**Comment by kolomparrudi** [comment]
I'm using Openpli with OWIF 1.0.2
