### ISSUE TITLE
packages: not working

### ISSUE THREAD

**Issue by koivo** [E2OpenPlugins/e2openplugin-OpenWebif#672]
Hi,

i think the packages option are not working correctly.
I have try it with openhdf and openatv.
Telnet show this messages:

07:32:46.0464 /usr/lib/python2.7/site-packages/twisted/logger/_file.py:66 __call__  Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1752, in lineReceived
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1845, in allContentReceived
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 766, in requestReceived
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 190, in process
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 241, in render
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/ipkg.py", line 51, in render
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/ipkg.py", line 174, in CallOPKList
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/ipkg.py", line 90, in getPackages
Exceptions.NameError: global name 'enumFeeds' is not defined

**Comment by koivo** [comment]
Hi,

i think this problem is not solved yet.
Do you have try it?
