### ISSUE TITLE
OpenPli 6 on vuduo2 freezes every day

### ISSUE THREAD

**Issue by florie1706** [E2OpenPlugins/e2openplugin-OpenWebif#709]
Hi there,

 

I have a problem with my vuduo2 receiver. It freezes ever day. I cant turn it on or do anything else, but the receiver is still accisible thru ssh. It is quite annyoing because timers dont go thru etc. I s there any solution for me, I actually dont understand the crashlog to fix it ...

`OpenPLi Enigma2 crash log

crashdate=Do Nov  9 03:58:29 2017
compiledate=Oct 30 2017
skin=PLi-FullHD/skin.xml
sourcedate=2017-10-29
branch=release-6.0
rev=4031322
component=enigma2, signal

stbmodel=duo2
stbmodel=dm8000
kernelcmdline=libata.force=1:1.5Gbps bmem=192M@64M bmem=220M@512M memc1=788M ubi.mtd=0 root=ubi0:rootfs rootfstype=ubifs rw rootflags=sync
nimsockets=NIM Socket 0:
imageissue=openpli 6.0-release %h

No handlers could be found for logger "AT"
ADD Peer Enigma2 Stream=vuzero-papa-2.local:8001
ADD Peer zero-blaues-zimmer=zero-blaues-zimmer.local:8001
ADD Peer vusolose=vusolose.local:8001
ADD Peer vusolose=vusolose.local:8001
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
REMOVE Peer Enigma2 Stream
REMOVE Peer zero-blaues-zimmer
REMOVE Peer vusolose
REMOVE Peer vuduo2
REMOVE Peer vusolose
REMOVE Peer vuduo2
ADD Peer vusolose=vusolose.local:8001
ADD Peer vusolose=vusolose.local:8001
ADD Peer Enigma2 Stream=vuzero-papa-2.local:8001
ADD Peer zero-blaues-zimmer=zero-blaues-zimmer.local:8001
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 31: invalid continuation byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 31: invalid continuation byte
PC: 770b6a68
    00000000 fffffffe 00000000 00000020
    00000003 7fc09690 00000000 00000000
    00000001 7fc09998 00000000 001d3067
    25097b42 ffffffff 00000000 76cb5090
    00000000 7fc09690 00000006 7fc097c8
    7fc09a14 00000061 00000073 00000073
    00000000 770b7584 00000010 00000000
    771e6e00 7fc095f8 fffffff7 770b69f4
-------FATAL SIGNAL`

or a second one is:

`OpenPLi Enigma2 crash log

crashdate=Sa Nov 11 03:56:33 2017
compiledate=Oct 30 2017
skin=PLi-FullHD/skin.xml
sourcedate=2017-10-29
branch=release-6.0
rev=4031322
component=enigma2, signal

stbmodel=duo2
stbmodel=dm8000
kernelcmdline=libata.force=1:1.5Gbps bmem=192M@64M bmem=220M@512M memc1=788M ubi.mtd=0 root=ubi0:rootfs rootfstype=ubifs rw rootflags=sync
nimsockets=NIM Socket 0:
imageissue=openpli 6.0-release %h

odeError: 'utf8' codec can't decode byte 0xdf in position 13: invalid continuation byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 4: invalid start byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 11: invalid continuation byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 4: invalid start byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 1: invalid continuation byte
INFO:AT:[AutoTimer] No changes in configuration, won't parse
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 31: invalid continuation byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 43: invalid start byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xdf in position 35: invalid continuation byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 14: invalid continuation byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xdf in position 13: invalid continuation byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 4: invalid start byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 11: invalid continuation byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 4: invalid start byte
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 1: invalid continuation byte
INFO:AT:[AutoTimer] No changes in configuration, won't parse
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1655, in lineReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1730, in allContentReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 826, in requestReceived
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
    
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 163, in render
    compstr = self.compressBuf(json.dumps(data))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 31: invalid continuation byte
PC: 766d6a68
    00000000 fffffffe 00000000 00000020
    00000003 7f8d95e0 00000000 00000000
    00000059 00000062 00000000 00000001
    7f8d9698 76833020 00000000 762b2bec
    00000000 7f8d95e0 00000006 7f8d9718
    7f8d9964 00000061 00000073 00000073
    0000005a 766d7584 00000010 00000000
    76806e00 7f8d9548 fffffff7 766d69f4
-------FATAL SIGNAL`

Thanx in advance for any hint or solution ;)

**Comment by jbleyel** [comment]
There is a problem with your epg data.
Probably your epg data not utf8 conform.

**Comment by florie1706** [comment]
Is this fix enough or do I need to change a setting or how do I get my epg data utf8 conform?

**Comment by jbleyel** [comment]
This change will only fix your crash and show you what openwebif request will make the crash.
Only if you know the exact request you will be able to find the root cause.
