### ISSUE TITLE
OWIF crashes when starting a stream 

### ISSUE THREAD

**Issue by WanWizard** [E2OpenPlugins/e2openplugin-OpenWebif#853]
when clicking on the stream icon. This was reported to us.

It doesn't happen al the time, I had to try a few times to reproduce it. The error:
````python
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Navigation.py", line 78, in dispatchRecordEvent
    x(rec_service, event)
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/stream.py", line 55, in requestWrite
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 234, in write
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1086, in write
AttributeError: 'NoneType' object has no attribute 'write'
````

**Comment by WanWizard** [comment]
This seems to be related to twisted. When the client disconnects, a ConnectionLost event is triggered in twisted that closes and cleans up the connection.

However, since OWIF doesn't listen to this event, it continues to call write on the request object, while the underlying connection object in twisted is already gone.

We've patched twisted for the time being to prevent this from happening, but ideally the root cause of this issue should be addressed?

**Comment by Dima73** [comment]
[stream.py] fix BSOD stop stream
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/pull/937

**Comment by jbleyel** [comment]
See here -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/pull/378
